#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <vector>

namespace lpLib
{
	class LP
	{
	public:
		static constexpr size_t VoiceCount = 32;
		static constexpr size_t Lp1RamWords = 136;
		using Voices = std::array<int32_t, VoiceCount>;
		using Lp1Ram = std::array<uint16_t, Lp1RamWords>;
		using Lp2Ram = std::array<uint16_t, VoiceCount>;
		using InterruptCallback = std::function<void(bool)>;
		struct VoiceState
		{
			int32_t volume;
			uint8_t bankMode;
			uint16_t step;
			uint8_t envelopeRate;
			uint8_t envelopeTarget;
			uint32_t address;
			uint16_t end;
			uint16_t loop;
			int32_t predictor;
			bool enabled;
		};

		explicit LP(const std::vector<uint8_t>& _rom);
		void reset();
		uint8_t read(uint8_t _offset);
		void write(uint8_t _offset, uint8_t _data);
		Voices renderSample();
		void setInterruptCallback(InterruptCallback _callback) { m_interrupt = std::move(_callback); }

		// The envelope curves are generated by shifts/adders and combinational
		// logic. Interpolation is read from the MB87420's physical 384 x 12-bit ROM.
		static int32_t envelopeLevel(uint8_t _value);
		static int32_t envelopeIncrement(uint8_t _value);
		static int32_t interpolationWeight(unsigned _tap, uint8_t _phase);

		bool voiceEnabled(unsigned _voice) const { return _voice < VoiceCount && m_voiceRuntime[_voice].enabled; }
		unsigned activeVoiceCount() const;
		VoiceState voiceState(unsigned _voice) const;
		bool interruptActive() const { return m_irqCurrentValid; }
		unsigned queuedInterrupts() const { return m_irqCount; }
		const Lp1Ram& lp1RamA() const { return m_lp1RamA; }
		const Lp1Ram& lp1RamB() const { return m_lp1RamB; }
		const Lp2Ram& lp2Ram() const { return m_lp2Ram; }

	private:
		struct VoiceRuntime
		{
			bool enabled = false;
			int8_t playDirection = 0;
			bool envelopeActive = false;
		};

		uint16_t parameterWord(unsigned _voice, unsigned _word) const;
		void setParameterWord(unsigned _voice, unsigned _word, uint16_t _value);
		int32_t currentVolume(unsigned _voice) const;
		void setCurrentVolume(unsigned _voice, int32_t _value);
		uint32_t currentAddress(unsigned _voice) const;
		void setCurrentAddress(unsigned _voice, uint32_t _value);
		int32_t predictor(unsigned _voice) const;
		void setPredictor(unsigned _voice, int32_t _value);
		static int16_t decodeSample(int8_t _data);
		uint8_t readRom(uint32_t _address) const;
		void signalEnvelopeComplete(uint8_t _voice);
		void setInterruptLine(bool _level);

		const std::vector<uint8_t>& m_rom;
		Lp1Ram m_lp1RamA{};
		Lp1Ram m_lp1RamB{};
		Lp2Ram m_lp2Ram{};
		std::array<VoiceRuntime, VoiceCount> m_voiceRuntime{};
		std::array<uint8_t, 0x100> m_registers{};
		std::array<uint8_t, VoiceCount> m_irqQueue{};
		uint8_t m_selected = 0;
		uint8_t m_irqRead = 0;
		uint8_t m_irqWrite = 0;
		uint8_t m_irqCount = 0;
		uint8_t m_irqVoice = 0;
		bool m_irqCurrentValid = false;
		uint16_t m_readback = 0;
		InterruptCallback m_interrupt;
	};
}
