#pragma once

// Portable board-side oracle runner for the isolated Filter F/092 kernel.
// The fixture is generated by nmmFilterF92Differential --emit-board and its
// expected hashes are produced by the DSP56300 interpreter.  This runner
// deliberately measures only runFilterF92; state construction and hashing
// are outside the cycle window.

#include "filter_f92_vectors.h"
#include "filter_f92_oracle.h"
#include "nmm101_kernels.h"

#include <array>
#include <cstddef>
#include <cstdint>

namespace nmm::native::teensy
{
struct FilterF92BoardResult
{
    std::size_t vectors = 0;
    std::size_t passed = 0;
    std::size_t failed = 0;
    std::size_t firstFailure = static_cast<std::size_t>(-1);
    uint64_t cyclesTotal = 0;
    uint32_t cyclesMin = 0;
    uint32_t cyclesMax = 0;
};

// CycleReader must be a cheap callable returning the target's free-running
// cycle counter.  A desktop caller can pass a monotonically increasing test
// counter; the board passes an inline ARM_DWT_CYCCNT read.
template<class CycleReader>
FilterF92BoardResult runFilterF92Vectors(CycleReader readCycles,
                                          uint32_t counterOverhead = 0) noexcept
{
    FilterF92BoardResult result;
    result.vectors = filter_f92_fixture::kVectorCount;
    std::array<Word24, filter_f92_oracle::kWords> x{};
    std::array<Word24, filter_f92_oracle::kWords> y{};

    for(std::size_t i = 0; i < result.vectors; ++i)
    {
        const auto& expected = filter_f92_fixture::kVectors[i];
        filter_f92_oracle::initialize(expected.index, expected.seed,
                                      x.data(), y.data());
        GraphMemory memory{x.data(), y.data(), x.size(), y.size(), false};
        ModuleCursor cursor;
        cursor.memory = &memory;
        cursor.r3 = expected.r3;
        cursor.r4 = expected.r4;

        const uint32_t begin = readCycles();
        // The isolated raw-template oracle uses X:0 for input/output.
        const Word24 output = runFilterF92(cursor, 0);
        const uint32_t end = readCycles();
        uint32_t cycles = end - begin;
        if(cycles >= counterOverhead)
            cycles -= counterOverhead;
        else
            cycles = 0;

        result.cyclesTotal += cycles;
        if(i == 0 || cycles < result.cyclesMin) result.cyclesMin = cycles;
        if(cycles > result.cyclesMax) result.cyclesMax = cycles;

        const uint64_t hash = filter_f92_oracle::hashState(
            x.data(), y.data(), static_cast<uint32_t>(cursor.r3),
            static_cast<uint32_t>(cursor.r4), cursor.a, cursor.b, cursor.x0,
            cursor.x1, cursor.y0, cursor.y1);
        const bool ok = !memory.fault && output == expected.output
                     && hash == expected.hash;
        if(ok)
            ++result.passed;
        else
        {
            ++result.failed;
            if(result.firstFailure == static_cast<std::size_t>(-1))
                result.firstFailure = expected.index;
        }
    }
    return result;
}
}
