// Watchdog timer (H8/510 hardware manual section 16).
//
// TCSR (read H'FF10):   OVF WT/IT TME 1 1 CKS2 CKS1 CKS0    reset H'18
// TCNT (read H'FF11):   8-bit up-counter, runs while TME = 1 (held at 0 otherwise)
// RSTCSR (read H'FF1F): WRST RSTOE 1 1 1 1 1 1              reset H'3F
//
// TCNT and TCSR are written only by a WORD write to H'FF10 whose upper byte is
// a password: H'5A -> TCNT, H'A5 -> TCSR.  RSTCSR is written by a word at
// H'FF1E: H'A500 clears WRST, H'5Axx writes RSTOE.  Byte writes are ignored.
//
// TCNT counts at phi / 2, 32, 64, 128, 256, 512, 2048, 4096 (CKS).  On
// overflow: interval mode (WT/IT = 0) sets OVF and requests the WDT interrupt
// (vector H'42, IRQ0 priority); watchdog mode (WT/IT = 1) sets WRST and
// resets the chip.  The counter is evaluated lazily; one event marks the
// overflow while the timer is enabled.
#pragma once
#include "cpu/h8500/bus.hpp"
#include "common/iomux.hpp"
#include "cpu/h8500/intc.hpp"
#include "common/sched.hpp"

namespace h8500 {

// Receives the internal reset generated by a watchdog overflow.
class ResetSink {
 public:
  virtual ~ResetSink() = default;
  virtual void watchdog_reset() = 0;
};

class Wdt final : public Device {
 public:
  static constexpr u8 kOvf = 0x80, kWtIt = 0x40, kTme = 0x20;
  static constexpr u8 kWrst = 0x80, kRstoe = 0x40;

  Wdt(emu::Scheduler& sched, const emu::Clock& clock, Intc& intc, u32 tcsr_addr, u32 rstcsr_addr);
  ~Wdt() override;

  void map(emu::IoMux& mux);
  // `by_watchdog`: the reset was generated by this module (WRST/RSTOE keep their values).
  void reset(bool by_watchdog = false);
  void set_reset_sink(ResetSink* s) { reset_sink_ = s; }

  u8 read8(u32 addr) override;
  void write8(u32 addr, u8 value) override;
  void write16(u32 addr, u16 value) override;

  u8 tcsr(u64 now) { sync(now); return u8(tcsr_ | 0x18); }
  u8 tcnt(u64 now) { sync(now); return tcnt_; }
  u8 rstcsr() const { return u8(rstcsr_ | 0x3F); }

 private:
  static void on_event(void* self, u64 when, u64 now);
  unsigned period_shift() const;
  bool running() const { return (tcsr_ & kTme) != 0; }
  u64 tick_of(u64 t) const { return t >> period_shift(); }
  void sync(u64 now);
  void overflow();
  void update_request();
  void reschedule();

  emu::Scheduler& sched_;
  const emu::Clock& clock_;
  Intc& intc_;
  ResetSink* reset_sink_ = nullptr;
  u32 tcsr_addr_;
  u32 rstcsr_addr_;
  emu::Scheduler::EventId event_ = 0;

  u8 tcsr_ = 0;       // bits 4-3 stored as 0, read as 1
  u8 tcnt_ = 0;
  u8 rstcsr_ = 0;     // bits 5-0 read as 1
  bool ovf_read_ = false;
  u64 tick_ = 0;
  u64 now_ = 0;
};

}  // namespace h8500
