set(ASSETS_xtDefault
	${CMAKE_CURRENT_LIST_DIR}/fxAmpMod.png
	${CMAKE_CURRENT_LIST_DIR}/fxAutoWahLP.png
	${CMAKE_CURRENT_LIST_DIR}/fxChorus.png
	${CMAKE_CURRENT_LIST_DIR}/fxDelay.png
	${CMAKE_CURRENT_LIST_DIR}/fxFlanger2.png
	${CMAKE_CURRENT_LIST_DIR}/fxModDelay.png
	${CMAKE_CURRENT_LIST_DIR}/fxOff.png
	${CMAKE_CURRENT_LIST_DIR}/fxOverdrive.png
	${CMAKE_CURRENT_LIST_DIR}/led.png
	${CMAKE_CURRENT_LIST_DIR}/xt_encoder_ranged.png
	${CMAKE_CURRENT_LIST_DIR}/xt_encoder_ranged_red.png
	${CMAKE_CURRENT_LIST_DIR}/xtDefaultBG.png
	${CMAKE_CURRENT_LIST_DIR}/xtknob.png
	${CMAKE_CURRENT_LIST_DIR}/xtknob_small.png
	${CMAKE_CURRENT_LIST_DIR}/xtPageArp.png
	${CMAKE_CURRENT_LIST_DIR}/xtPageMod.png
	${CMAKE_CURRENT_LIST_DIR}/xtPageMulti.png
	${CMAKE_CURRENT_LIST_DIR}/xtPageOsc.png
	${CMAKE_CURRENT_LIST_DIR}/xtPagePatchManager.png

	${CMAKE_CURRENT_LIST_DIR}/xtDefault.json
)
