#!/usr/bin/env python3
"""Generate a local full 0x800-word X/Y fixture from reference snapshots.

The generated header is deliberately a build artifact: it embeds the pinned
reference capture, while the source tree retains the compact checked-in
acceptance vectors in nord101_reference_state.h.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


WORDS = 0x800
WORD_BYTES = 3
EXPECTED = {
    "x": "b803f5c4e4d43ccf40bf970c89f25b798be4123066564263402a98c144a7be90",
    "y": "77c27b3a5623a25cf2b754222f80cddec18fa22e498056e3f64bb507093428b1",
}


def load(path: Path, space: str) -> list[int]:
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED[space]:
        raise SystemExit(f"{space} snapshot hash mismatch: {digest}")
    if len(data) < WORDS * WORD_BYTES:
        raise SystemExit(f"{space} snapshot is shorter than 0x800 words: {len(data)}")
    data = data[: WORDS * WORD_BYTES]
    return [int.from_bytes(data[index : index + WORD_BYTES], "big") for index in range(0, len(data), WORD_BYTES)]


def emit(space: str, values: list[int]) -> str:
    lines = [f"constexpr std::uint32_t k101Ready{space.upper()}Full[0x800] = {{"]
    for index in range(0, WORDS, 8):
        lines.append("    " + ", ".join(f"0x{value:06x}u" for value in values[index : index + 8]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("reference_dir", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    x = load(args.reference_dir / "warmup_dsp_x.bin", "x")
    y = load(args.reference_dir / "warmup_dsp_y.bin", "y")
    text = """// Generated by generate_101_reference_state.py.\n// Firmware SHA-256: 0ccbffa696f4aa65baa53768695dc02b3afa61ce572006b532cf278515759c3c\n// Patch SHA-256: 1960af3ab94ec9317284eb5b877f1dc133e2094da72238e86424a98487ffbef8\n#pragma once\n#include <cstdint>\nnamespace nmm::native::mcu\n{\n"""
    text += emit("x", x) + "\n\n" + emit("y", y)
    text += "\n} // namespace nmm::native::mcu\n"
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="ascii")


if __name__ == "__main__":
    main()
