set(ASSETS_n2xTrancy
	${CMAKE_CURRENT_LIST_DIR}/background.png
	${CMAKE_CURRENT_LIST_DIR}/button_a.png
	${CMAKE_CURRENT_LIST_DIR}/button_b.png
	${CMAKE_CURRENT_LIST_DIR}/button_black.png
	${CMAKE_CURRENT_LIST_DIR}/button_browser.png
	${CMAKE_CURRENT_LIST_DIR}/button_c.png
	${CMAKE_CURRENT_LIST_DIR}/button_d.png
	${CMAKE_CURRENT_LIST_DIR}/button_main.png
	${CMAKE_CURRENT_LIST_DIR}/button_perf.png
	${CMAKE_CURRENT_LIST_DIR}/button_red.png
	${CMAKE_CURRENT_LIST_DIR}/button_round.png
	${CMAKE_CURRENT_LIST_DIR}/DSEG7Classic-BoldItalic.ttf
	${CMAKE_CURRENT_LIST_DIR}/DSEG14Classic-BoldItalic.ttf
	${CMAKE_CURRENT_LIST_DIR}/h_slider.png
	${CMAKE_CURRENT_LIST_DIR}/knob_big.png
	${CMAKE_CURRENT_LIST_DIR}/knob_big_sens.png
	${CMAKE_CURRENT_LIST_DIR}/panel_1_main.png
	${CMAKE_CURRENT_LIST_DIR}/panel_1_main_arpeggiator.png
	${CMAKE_CURRENT_LIST_DIR}/panel_1_main_lfo2.png
	${CMAKE_CURRENT_LIST_DIR}/panel_2_browser.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_perf.png

	${CMAKE_CURRENT_LIST_DIR}/n2xTrancy.json
)
