set(ASSETS_VirusTI_Trancy
	${CMAKE_CURRENT_LIST_DIR}/background.png
	${CMAKE_CURRENT_LIST_DIR}/button_1.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_1.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_10.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_11.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_12.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_13.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_14.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_15.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_16.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_2.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_3.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_4.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_5.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_6.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_7.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_8.png
	${CMAKE_CURRENT_LIST_DIR}/button_channel_9.png
	${CMAKE_CURRENT_LIST_DIR}/button_load.png
	${CMAKE_CURRENT_LIST_DIR}/button_menu.png
	${CMAKE_CURRENT_LIST_DIR}/button_mono_poly.png
	${CMAKE_CURRENT_LIST_DIR}/button_multi.png
	${CMAKE_CURRENT_LIST_DIR}/button_next.png
	${CMAKE_CURRENT_LIST_DIR}/button_plus.png
	${CMAKE_CURRENT_LIST_DIR}/button_prev.png
	${CMAKE_CURRENT_LIST_DIR}/button_save.png
	${CMAKE_CURRENT_LIST_DIR}/button_single.png
	${CMAKE_CURRENT_LIST_DIR}/button_slow_fast.png
	${CMAKE_CURRENT_LIST_DIR}/button_sub.png
	${CMAKE_CURRENT_LIST_DIR}/Digital.ttf
	${CMAKE_CURRENT_LIST_DIR}/knob_big.png
	${CMAKE_CURRENT_LIST_DIR}/knob_mid.png
	${CMAKE_CURRENT_LIST_DIR}/knob_small.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_arp.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_browser.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_common.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_filter.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_fx1.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_fx2.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_lfo.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_main.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_matrix.png
	${CMAKE_CURRENT_LIST_DIR}/mainbutton_osc.png
	${CMAKE_CURRENT_LIST_DIR}/panel_1_easy_edit.png
	${CMAKE_CURRENT_LIST_DIR}/panel_10_common.png
	${CMAKE_CURRENT_LIST_DIR}/panel_2_browser.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc_classic.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc_grain_complex.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc_grain_simple.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc_hypersaw.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc_wave_pwm.png
	${CMAKE_CURRENT_LIST_DIR}/panel_3_osc_wavetable.png
	${CMAKE_CURRENT_LIST_DIR}/panel_4_filter.png
	${CMAKE_CURRENT_LIST_DIR}/panel_5_lfo.png
	${CMAKE_CURRENT_LIST_DIR}/panel_6_matrix.png
	${CMAKE_CURRENT_LIST_DIR}/panel_7_arp.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_chorus_air_chorus.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_chorus_classic.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_chorus_hyper_chorus.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_chorus_vibrato.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_chorus_vintage.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_filterbank_frequency_shift.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_filterbank_pole_xfade.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_filterbank_ringmodulator.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_filterbank_vari_slopes.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_filterbank_vowel_filter.png
	${CMAKE_CURRENT_LIST_DIR}/panel_8_fx1_rotary_speaker.png
	${CMAKE_CURRENT_LIST_DIR}/panel_9_fx2.png
	${CMAKE_CURRENT_LIST_DIR}/panel_9_fx2_delay_tape.png
	${CMAKE_CURRENT_LIST_DIR}/slider_knob.png

	${CMAKE_CURRENT_LIST_DIR}/VirusTI_Trancy.json
)
