// Watchdog timer (SH7014 hardware manual section 11).
//
// TCSR   (read H'FFFF8610): OVF WT/IT TME 1 1 CKS2 CKS1 CKS0    reset H'18
// TCNT   (read H'FFFF8611): 8-bit up-counter, runs while TME = 1 (held at 0 otherwise)
// RSTCSR (read H'FFFF8613): WOVF RSTE 0 1 1 1 1 1              reset H'1F
//
// TCNT and TCSR are written only by a WORD write to H'FFFF8610 whose upper
// byte is a password (11.2.4): H'5A -> TCNT, H'A5 -> TCSR.  RSTCSR is written
// by a word at H'FFFF8612: H'A500 clears WOVF (after it was read as 1),
// H'5Axx writes RSTE.  Byte and longword writes are ignored.
//
// TCNT counts at phi / 2, 64, 128, 256, 512, 1024, 4096, 8192 (CKS2-0, table
// in 11.2.2).  On the H'FF -> H'00 overflow:
//   * interval timer mode (WT/IT = 0): OVF is set and ITI (vector 152) is
//     requested while OVF = 1 (11.3.2, 11.3.4);
//   * watchdog mode (WT/IT = 1): WOVF is set, the WDTOVF pin goes low for
//     128 states, TCNT and TCSR are reset inside the module (11.4.5) and, if
//     RSTE = 1, an internal reset of the whole chip is generated through the
//     reset sink (11.3.1).  The SH7014 has no RSTS bit (RSTCSR bit 5 is
//     reserved): the internal reset is a power-on reset that leaves RSTCSR,
//     the PFC and the I/O port registers untouched.
// The counter is lazy (a function of the state clock, synced on access) with
// one scheduler event for the next overflow that has an effect.
// Out of scope: the standby-mode wake-up count (11.3.3) and the register
// initialisation on entering standby.
#pragma once
#include <functional>

#include "common/iomux.hpp"
#include "common/sched.hpp"
#include "cpu/sh2/bus.hpp"
#include "cpu/sh2/intc.hpp"

namespace sh2 {

// Receives the internal reset generated by a watchdog overflow with RSTE = 1
// (the Machine implements it: reset everything except the WDT's RSTCSR).
class WdtResetSink {
 public:
  virtual ~WdtResetSink() = default;
  virtual void watchdog_reset() = 0;
};

class Wdt final : public Device {
 public:
  static constexpr u32 kTcsr = 0xFFFF8610u, kTcnt = 0xFFFF8611u;
  static constexpr u32 kRstcsrW = 0xFFFF8612u, kRstcsrR = 0xFFFF8613u;
  // TCSR bits
  static constexpr u8 kOvf = 0x80, kWtIt = 0x40, kTme = 0x20, kCksMask = 0x07;
  // RSTCSR bits
  static constexpr u8 kWovf = 0x80, kRste = 0x40;
  // WDTOVF is driven low for 128 states after a watchdog-mode overflow (11.3.1).
  static constexpr u64 kWdtovfPulse = 128;
  static constexpr u64 kInternalResetPulse = 512;  // informational: length of the internal reset signal

  // Called with the exact state of a watchdog-mode overflow (the falling edge of WDTOVF).
  using WdtovfCallback = std::function<void(u64 at)>;

  // base: TCSR read address (H'FFFF8610 on the SH7014, H'5FFFFB8 on the SH7034).
  Wdt(emu::Scheduler& sched, const emu::Clock& clock, Intc& intc, u32 base = kTcsr);
  ~Wdt() override;

  void map(emu::IoMux& mux);
  // `by_watchdog`: the reset was generated by this module (RSTCSR keeps its value, 11.2.3).
  void reset(bool by_watchdog = false);
  void set_reset_sink(WdtResetSink* s) { reset_sink_ = s; }
  void set_wdtovf_callback(WdtovfCallback cb) { wdtovf_ = std::move(cb); }

  u8 read8(u32 addr) override;
  void write8(u32 addr, u8 value) override;
  void write16(u32 addr, u16 value) override;
  void write32(u32 addr, u32 value) override;

  // --- host side --------------------------------------------------------------
  u8 tcsr(u64 now) { sync(now); return u8(tcsr_ | 0x18); }
  u8 tcnt(u64 now) { sync(now); return tcnt_; }
  u8 rstcsr() const { return u8(rstcsr_ | 0x1F); }
  // WDTOVF pin level (active low) at state `now`.
  bool wdtovf_low(u64 now) const { return now >= wdtovf_at_ && now < wdtovf_at_ + kWdtovfPulse; }

 private:
  static void on_event(void* self, u64 when, u64 now);
  unsigned period_shift() const;
  bool running() const { return (tcsr_ & kTme) != 0; }
  u64 tick_of(u64 t) const { return t >> period_shift(); }
  void sync(u64 now);
  void overflow(u64 at);
  void update_request();
  void reschedule();

  u32 base_;
  emu::Scheduler& sched_;
  const emu::Clock& clock_;
  Intc& intc_;
  WdtResetSink* reset_sink_ = nullptr;
  WdtovfCallback wdtovf_;
  emu::Scheduler::EventId event_ = 0;

  u8 tcsr_ = 0;    // bits 4-3 stored as 0, read as 1
  u8 tcnt_ = 0;
  u8 rstcsr_ = 0;  // bits 4-0 read as 1, bit 5 as 0
  bool ovf_read_ = false;
  bool wovf_read_ = false;
  u64 tick_ = 0;
  u64 now_ = 0;
  u64 wdtovf_at_ = ~u64(0);  // state of the last watchdog overflow (kNever when none)
};

}  // namespace sh2
