#pragma once
#include <array>
#include <cstdint>
#include <string>
#include <istream>
#include <vector>

namespace nmm
{
	// Editor patch data only. Module DSP code is generated by the original OS.
	struct Patch
	{
		struct Module { uint16_t area, index, type; uint8_t x=0,y=0; std::string name; };
		struct Parameter { uint16_t area, module, index, value; };
		struct Knob { uint16_t area, module, parameter, index; };
		struct Cable { uint16_t area; std::array<uint8_t, 6> record; };
		struct Custom { uint16_t area,module; std::vector<uint8_t> data; };
        struct Morph { uint16_t area, module, parameter, group; int16_t range; };
		uint8_t keyRangeMin=0, keyRangeMax=127, velocityRangeMin=0, velocityRangeMax=127;
		uint8_t requestedVoices=1;
		std::string name="Init";
		uint8_t bendRange=2, voiceRetrigger=1, commonRetrigger=1;
        uint8_t portamento=0,portamentoTime=0,octaveShift=2;
        uint16_t areaSeparator=4000;
        std::vector<Knob> controllers;
        std::vector<Custom> custom;
		std::vector<Module> modules;
		std::vector<Parameter> parameters;
		std::vector<Cable> cables;
		std::vector<Knob> knobs;
		std::array<uint8_t,4> morphValues{};
		std::array<uint8_t,4> morphKeyboard{};
		std::vector<Morph> morphs;
		static Patch load(const std::string& filename);
		static Patch parse(std::istream& input);
	};
}
